import { clientsClaim } from "workbox-core";
import { precacheAndRoute } from "workbox-precaching";

// Self-skip waiting to activate the service worker immediately
self.skipWaiting();
clientsClaim();

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle push notifications
self.addEventListener("push", (event) => {
  const data = event.data.json();
  const { title, body } = data;

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon: "/pwa-192x192.png",
    })
  );
});

// Handle notification clicks
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  event.waitUntil(
    clients.openWindow("/")
  );
});